######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 17 13:41:18 2008
######################################################################

TEMPLATE = app
SOURCES += main.cpp
include($$PWD/textedit.pri)
CONFIG -= app_bundle
DEFINES += TEXTDOCUMENT_LINENUMBER_CACHE
release {
    QMAKE_CXXFLAGS += -g
}
