######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 18 18:56:23 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += tst_textdocument.cpp
CONFIG += debug
CONFIG -= app_bundle
DEFINES += TEXTDOCUMENT_FIND_SLEEP LAZYTEXTEDIT_AUTOTEST

unix {
    MOC_DIR=.moc
    UI_DIR=.ui
    OBJECTS_DIR=.obj
} else {
    MOC_DIR=tmp/moc
    UI_DIR=tmp/ui
    OBJECTS_DIR=tmp/obj
}
load(qtestlib.prf)
include(../../textedit.pri)

